title: Atrakcje Malty
description: Przewodnik po wyspie
theme: minima
nav_pages:
  - title: Strona Główna
    url: /index.html
  - title: Valletta
    url: /valletta.html
  - title: Mdina i Gozo
    url: /mdina-gozo.html
# Ustawienia dodatkowe
show_excerpts: true
header_pages:
  - index.md
  - valletta.md
  - mdina-gozo.md
sass:
  style: compressed
